"""Comment-thread investigation analyzer — the part that reads the ticket like a
human debug engineer does.

A ticket's comment thread IS the investigation: who observed what, what was tried,
what was ruled out, and where the debug converged (root cause / workaround). The
signature/log scan alone misses all of this. This module mines the structured
comments (author + order preserved) into a crystal-clear narrative:

  - a chronological investigation timeline (per comment: kind + concise point),
  - the CONVERGED root cause (latest strong statement wins — debug converges),
  - any workaround / fix mentioned,
  - what has ALREADY been tried (so next steps don't repeat them),
  - technical breadcrumbs (registers, file:line, socket/port, BIOS builds, logs).

Deterministic (no LLM). Heuristics are conservative and quote the ticket text.
"""

import re
from typing import Any, Dict, List, Optional

# --- classification cues (checked in priority order; first match wins) ---
_KIND_CUES: List[tuple] = [
    ("root_cause", re.compile(
        r"root[\s-]?cause|isolated (?:the )?issue to|isolated to|culprit|"
        r"caused by|due to|because of|leading to|leads to|results? in|"
        r"stuck (?:state|indefinitely)|\bNACK\b|no[\s-]?ack|never (?:reach|recover|"
        r"receive)|not received|hang(?:s)? (?:before|because|when|at)", re.I)),
    ("workaround", re.compile(
        r"work[\s-]?around|\bW/?A\b|temporary (?:fix|workaround)|mitigat|\bBKM\b|"
        r"patched|real fix|proper fix|fix (?:in progress|is|lands|validated)", re.I)),
    ("finding", re.compile(
        r"observ|confirm|reproduc|recreat|\bseen\b|shows?|indicat|detect|found|"
        r"non[\s-]?zero|error(?:s)? (?:detected|re-?assert)|re-?assert|clean|"
        r"experiments? confirm|points? to", re.I)),
    ("action", re.compile(
        r"tried|flash(?:ed|ing)|disabl(?:ed|ing)|enabl(?:ed|ing)|swap|re-?ran|"
        r"re-?run|provided (?:a )?(?:test|debug)|reach(?:ed)? out|promoted to|"
        r"add(?:ed|ing)? (?:extra |debug )?logs|check(?:ed|ing)?|poll|trace|"
        r"bisect|A/B|isolate whether", re.I)),
    ("next_step", re.compile(
        r"next(?:\s*step)?|will (?:try|check|add|work)|working on|plan to|to check|"
        r"need to|todo|going to|follow[\s-]?up", re.I)),
]

# --- technical breadcrumb extractors ---
_BREADCRUMBS: List[tuple] = [
    ("register", re.compile(r"\b[A-Z][A-Z0-9]{3,}_[A-Z0-9_]*REG\b|\bBIOSSCRATCHPAD\d+\w*", re.I)),
    ("code_site", re.compile(r"\b[\w]+\.c:\d+\b", re.I)),
    ("socket_port", re.compile(
        r"\bSocket\s*\d+\b|\bPort\s*\d+\b|UpiAgent\[\d\]\[\d\]|Cpu\d+P\d+KitPortDisable", re.I)),
    ("bios_build", re.compile(r"\b[A-Z]{3,}\d*\.[A-Z]{2,4}\.\d{3,4}\.[A-Za-z0-9._]+", re.I)),
    ("upi_signal", re.compile(r"\bKTI[A-Z0-9_]+REG\b|\bUPLR\d(?:\.\d)?\b", re.I)),
]

_LABELS = {
    "root_cause": "ROOT CAUSE",
    "workaround": "WORKAROUND / FIX",
    "finding": "OBSERVED",
    "action": "TRIED",
    "next_step": "NEXT STEP",
    "note": "NOTE",
}

# strong convergence markers boost a comment's claim to be THE root cause
_STRONG_RC = re.compile(
    r"isolated (?:the )?issue to|root[\s-]?caused?|\bNACK\b|stuck (?:state|indefinitely)|"
    r"never (?:reaches?|recover)|not received|hang.*(?:because|due to|before)", re.I)

# Meta-pointer / referential phrases — these MENTION "root cause" but do NOT assert
# one (e.g. "here is Nick AI analysis, interesting hypothesis in the root cause
# section"). They must never be treated as the converged root cause.
_META_POINTER = re.compile(
    r"root[\s-]?cause section|in the root[\s-]?cause section|"
    r"here (?:is|are|'s)\b[^.]*\banalysis\b|interesting hypothesis|"
    r"if you want to skip|skip some of the context|"
    r"see (?:the )?(?:attached|analysis|root[\s-]?cause)|"
    r"refer to (?:the )?(?:attached|analysis|section|doc)", re.I)

# A pasted AI/tool analysis (e.g. "Nick AI analysis") is a HYPOTHESIS, not a
# validated engineer disposition — flag its provenance so the report can say so.
_AI_ANALYSIS = re.compile(
    r"\bAI analysis\b|AI-?generated|\bNick\b[^.]{0,20}analysis|\bhypothesis\b|"
    r"generated by (?:an? )?(?:AI|model|llm)|\bLLM\b analysis|automated analysis", re.I)



# closure / resolution / disposition statements (final verdict of the thread)
_RESOLUTION = re.compile(
    r"no repro|cannot reproduce|not able to reproduce|issue (?:is )?not seen|"
    r"after (?:set|setting|applying|flashing).*(?:not seen|resolved|fixed|no repro)|"
    r"closing as|closed as|marking .* (?:closed|rejected)|fixed (?:in|by)|"
    r"resolved (?:by|in|after)|root[\s-]?caused to|will be fixed in|"
    r"work[\s-]?around", re.I)


def _is_prose(s: str) -> bool:
    """True for human explanation; False for tables / log dumps / timestamp grids
    so we don't mistake a pasted test-indicator table for a root-cause statement."""
    if s.count("|") >= 3 or s.count("@") >= 2:
        return False
    if re.search(r"\d{4} @ \d|kubernetes\.host|metadata\.test|test-(?:start|end)-indicator",
                 s, re.I):
        return False
    if any(tok in s for tok in ("0x", "::", "=>", ".show()", ".read()", "sv.socket")):
        # allow short mentions but reject dump-like lines
        if len(re.findall(r"0x[0-9A-Fa-f]+", s)) >= 2:
            return False
    alpha = sum(c.isalpha() or c.isspace() for c in s)
    return len(s) >= 12 and alpha / max(1, len(s)) >= 0.6


def _split_sentences(text: str) -> List[str]:
    # Normalize ASCII banners / rule lines (====, ----, ****, ~~~~) into sentence
    # breaks so a pasted report's separators never glue onto real prose.
    text = re.sub(r"[=_~*]{3,}", ". ", text)
    text = re.sub(r"-{4,}", ". ", text)
    parts = re.split(r"(?<=[.;!?])\s+|\n+", text)
    return [p.strip(" .=_*~") for p in parts if len(p.strip(" .=_*~")) >= 8]


# --- labeled "ROOT CAUSE" section extractor (for pasted RCA docs) ------------
_RC_LABEL = re.compile(r"root[\s_-]?cause\b", re.I)
# "root cause analysis/section/tab/doc" is a reference, not the labeled section.
_RC_LABEL_SKIP = re.compile(r"^root[\s_-]?cause\s+(?:analysis|section|tab|doc|report|memo)",
                            re.I)
# The labeled section is only useful if it carries a substantive mechanism.
_RC_SUBSTANTIVE = re.compile(
    r"0x[0-9a-f]+|missing|absent|not programmed|because|due to|reset|default|"
    r"underflow|\bNACK\b|never|stuck|degrad|lower bandwidth", re.I)


def _labeled_root_cause(text: str) -> str:
    """Pull the substantive text under a 'ROOT CAUSE[:]' heading in a pasted RCA
    block (e.g. Nick AI analysis). Ignores banner rules and reference titles like
    'Root Cause Analysis'. Returns '' when no substantive labeled cause is found."""
    t = re.sub(r"[=_~*]{2,}|-{3,}", " ", text)
    t = re.sub(r"\s+", " ", t).strip()
    best = ""
    for m in _RC_LABEL.finditer(t):
        seg = t[m.start(): m.start() + 400]
        if _RC_LABEL_SKIP.match(seg):
            continue
        if _RC_SUBSTANTIVE.search(seg) and len(seg) > len(best):
            best = seg
    return best[:400]


# --- full per-comment digest extractors (human-triage detail, nothing dropped) -
# Labeled write-up headers engineers use ("Issue:", "Expected Behavior:", ...).
# Longest labels first so "Expected Behavior" wins over "Expected".
_FIELD_LABELS = sorted([
    "Issue", "Impact", "Expected Behavior", "Expected", "Actual",
    "Reference Observation", "Scope", "Evidence", "Steps to reproduce", "Steps",
    "Expectation", "Observation", "Key Observation", "Passing case",
    "Failing case", "Failure case", "Conclusion", "Root cause", "Workaround",
    "Update", "Summary", "Analysis", "Next steps", "Next step", "Recommendation",
    "Fix", "Trigger", "Reproduction", "Repro", "Result", "Note",
], key=len, reverse=True)
_FIELD_HEADER = re.compile(
    r"\b(" + "|".join(re.escape(l) for l in _FIELD_LABELS) + r")\s*:\s*", re.I)

# Leading working-week / update tag, e.g. "WW29.3 Update", "WW28.5".
_LEADING_TAG = re.compile(r"^\s*(WW\s*\d+(?:\.\d+)?(?:\s+Update)?)\s*[:\-]?\s*", re.I)

# Register decode with an inline "==> meaning" annotation (the smoking gun).
_REG_ANNOTATED = re.compile(
    r"([A-Za-z_][\w ]*?)\s*:\s*(0x[0-9A-Fa-f]+)\s*==>\s*(.+?)"
    r"(?=\s+[A-Za-z_][\w ]*?\s*:\s*0x|\s+Out\[|\s+In \[|$)")
# Named reset-cause / status register with a value word, e.g.
# "GBLRST_CAUSE1 0x8000e488 0x00000004".
_REG_VALUE = re.compile(
    r"\b([A-Z][A-Z0-9]{2,}(?:_[A-Z0-9]+)*\s*\d*)\s+0x[0-9A-Fa-f]+\s+(0x[0-9A-Fa-f]+)")
# Operator-issued commands worth preserving verbatim.
_COMMAND = re.compile(
    r"((?:gpioset|gpiofind|python|rdmsr|wrmsr|xmlcli|ipmitool)\b[^\n]*?)"
    r"(?=\s+(?:Expectation|Actual|Expected|Impact|Issue|Scope|Evidence|Conclusion)\s*:|$)",
    re.I)
# One experiment row from a pass/fail matrix.
_EXPERIMENT = re.compile(r"(Exp\s*\d+.*?(?:✅|❌)\s*Issue(?: Not)? Seen)", re.I | re.S)


def _leading_tag(text: str) -> str:
    m = _LEADING_TAG.match(text)
    return m.group(1).strip() if m else ""


def _labeled_fields(text: str) -> List[tuple]:
    """Split a comment into its (label, value) write-up fields, in order."""
    out: List[tuple] = []
    marks = list(_FIELD_HEADER.finditer(text))
    for i, m in enumerate(marks):
        label = m.group(1).title()
        start = m.end()
        end = marks[i + 1].start() if i + 1 < len(marks) else len(text)
        val = re.sub(r"\s+", " ", text[start:end]).strip(" .;-")
        # Trim a register/PythonSV dump tail and any pasted experiment matrix so a
        # field stays human-readable (the matrix is captured separately).
        val = re.split(r"\bIn \[\d+\]:|\bOut\[\d+\]:|\bExperiment\s+Base|\bExp\s*1\b|"
                       r"\s+INFO\s+\|", val)[0].strip(" .;-")
        if val:
            out.append((label, val[:400]))
    return out


def _register_evidence(text: str) -> List[str]:
    """Extract register state that pins the failure (value + inline meaning)."""
    out: List[str] = []
    for m in _REG_VALUE.finditer(text):
        nm = re.sub(r"\s+", "", m.group(1))
        out.append(f"{nm} = {m.group(2)}")
    for m in _REG_ANNOTATED.finditer(text):
        note = re.sub(r"\s+", " ", m.group(3)).strip(" .;-")
        note = re.split(r"\s+INFO\b|\s+In \[|\s+Out\[", note)[0].strip(" .;-")
        if note:
            out.append(f"{m.group(1).strip()} = {m.group(2)} ⇒ {note[:80]}")
    return list(dict.fromkeys(out))[:12]


def _commands(text: str) -> List[str]:
    hits = [re.sub(r"\s+", " ", m.group(1)).strip(" .") for m in _COMMAND.finditer(text)]
    return list(dict.fromkeys(h for h in hits if len(h) >= 6))[:8]


def _experiments(text: str) -> List[str]:
    hits = [re.sub(r"\s+", " ", m.group(1)).strip() for m in _EXPERIMENT.finditer(text)]
    return list(dict.fromkeys(hits))[:12]


def _digest_comment(text: str) -> Dict[str, Any]:
    """Full human-triage digest of ONE comment — nothing important dropped."""
    return {
        "tag": _leading_tag(text),
        "fields": _labeled_fields(text),
        "registers": _register_evidence(text),
        "commands": _commands(text),
        "experiments": _experiments(text),
    }


def _is_experiment_matrix(s: str) -> bool:
    """True for a pasted pass/fail experiment table row/block — it is evidence,
    not a disposition, so it must not be read as closure or a workaround."""
    if s.count("✅") + s.count("❌") >= 2:
        return True
    return bool(re.search(r"\bExp\s*\d+\b.*\bExp\s*\d+\b", s))


# Handoff: the thread converged but was promoted to another team for the fix.
_HANDOFF = re.compile(
    r"promote(?:d)? to\s+(?P<team1>[A-Za-z0-9 /_-]{2,40}?)\s+(?:team|for further)|"
    r"hand(?:ed)?[\s-]?off to|assigned to\s+(?P<team2>[A-Za-z0-9 /_-]{2,40}?)\s+team|"
    r"further steps", re.I)


def _classify(sentence: str) -> Optional[str]:
    for kind, pat in _KIND_CUES:
        if pat.search(sentence):
            # A referential mention of "root cause" (pointer to an analysis/section)
            # is not an assertion — skip it and keep checking the other cues.
            if kind == "root_cause" and _META_POINTER.search(sentence):
                continue
            return kind
    return None


def _salient(text: str) -> Dict[str, str]:
    """Pick the most salient PROSE sentence + kind from one comment (root_cause >
    workaround > finding > action > next_step). Non-prose (tables/log dumps) is
    skipped so noise never becomes the headline."""
    order = {k: i for i, (k, _) in enumerate(_KIND_CUES)}
    best_kind, best_sent = None, ""
    prose = [s for s in _split_sentences(text) if _is_prose(s)]
    for s in prose:
        k = _classify(s)
        if k is None:
            continue
        if best_kind is None or order[k] < order[best_kind]:
            best_kind, best_sent = k, s
        if best_kind == "root_cause":
            break
    if best_kind is None:
        return {"kind": "note", "text": (prose[0] if prose else
                                         (_split_sentences(text)[:1] or [text])[0])[:240]}
    return {"kind": best_kind, "text": best_sent[:240]}


def _breadcrumbs(text: str) -> Dict[str, List[str]]:
    out: Dict[str, List[str]] = {}
    for name, pat in _BREADCRUMBS:
        hits = list(dict.fromkeys(m.group(0) for m in pat.finditer(text)))
        if hits:
            out[name] = hits[:12]
    return out


def analyze_comments(structured: List[Dict[str, str]]) -> Optional[Dict[str, Any]]:
    """Return the mined investigation narrative, or None if no comments."""
    if not structured:
        return None

    narrative: List[Dict[str, str]] = []
    tried: List[str] = []
    next_steps: List[str] = []
    crumbs: Dict[str, List[str]] = {}
    rc_candidates: List[tuple] = []      # (index, strength, author, text)
    wa_candidates: List[tuple] = []
    res_candidates: List[tuple] = []     # (index, author, text) — closure/disposition

    for idx, c in enumerate(structured):
        author = c.get("author", "") or "unknown"
        text = c.get("text", "") or ""
        if not text:
            continue
        sal = _salient(text)
        narrative.append({"seq": idx + 1, "author": author,
                          "kind": sal["kind"], "text": sal["text"],
                          "digest": _digest_comment(text)})

        # accumulate breadcrumbs across the whole thread
        for k, v in _breadcrumbs(text).items():
            crumbs.setdefault(k, [])
            for item in v:
                if item not in crumbs[k]:
                    crumbs[k].append(item)

        # root-cause candidates: PROSE only; later comments + strong markers win
        for s in _split_sentences(text):
            if not _is_prose(s):
                continue
            if _classify(s) == "root_cause":
                strength = idx + (5 if _STRONG_RC.search(s) else 0)
                rc_candidates.append((idx, strength, author, s[:300], "comment_statement"))
            # A pass/fail experiment matrix ("✅ Issue Not Seen") is EVIDENCE, not a
            # closure or a workaround — never let it masquerade as either.
            if _is_experiment_matrix(s):
                continue
            if _RESOLUTION.search(s):
                res_candidates.append((idx, author, s[:300]))
            if _classify(s) == "workaround":
                wa_candidates.append((idx, author, s[:240]))
        # A pasted RCA doc with a labeled "ROOT CAUSE:" section is the strongest
        # possible statement — extract its substantive text and rank it top.
        labeled = _labeled_root_cause(text)
        if labeled:
            src = "ai_analysis" if _AI_ANALYSIS.search(text) else "labeled_section"
            rc_candidates.append((idx, idx + 20, author, labeled, src))


        if sal["kind"] == "action":
            tried.append(f"{author}: {sal['text']}")
        if sal["kind"] == "next_step":
            next_steps.append(f"{author}: {sal['text']}")

    root_cause = ""
    rc_author = ""
    rc_source = ""
    if rc_candidates:
        rc_candidates.sort(key=lambda x: x[1], reverse=True)
        _, _, rc_author, root_cause, rc_source = rc_candidates[0]

    # Enrich a comment-sourced root cause with the strongest mechanism field
    # (Conclusion / Key Observation / Trigger) from the SAME author's thread, so
    # the headline carries the "why", not just the one-line claim.
    if root_cause and rc_source in ("comment_statement", "labeled_section"):
        mech = ""
        for c in structured:
            for lbl, val in _labeled_fields(c.get("text", "") or ""):
                if lbl in ("Conclusion", "Key Observation", "Trigger") and len(val) > len(mech):
                    mech = val
        if mech and mech[:40].lower() not in root_cause.lower():
            root_cause = f"{root_cause.rstrip('. ')}. {mech}"[:600]

    # Resolution / closure statement (final disposition) — latest wins.
    resolution = ""
    res_author = ""
    if res_candidates:
        res_candidates.sort(key=lambda x: x[0], reverse=True)
        _, res_author, resolution = res_candidates[0]

    workaround = ""
    wa_author = ""
    if wa_candidates:
        # prefer the latest workaround mention
        wa_candidates.sort(key=lambda x: x[0], reverse=True)
        _, wa_author, workaround = wa_candidates[0]
    # A closure/resolution statement is also a valid "workaround/fix" headline.
    if not workaround and resolution:
        workaround, wa_author = resolution, res_author

    # If we have a closure but no prose root cause, use the resolution as the
    # converged conclusion (e.g. "after setting CPU straps, no repro").
    if not root_cause and resolution:
        root_cause, rc_author = resolution, res_author
        rc_source = "resolution"

    # status hint from the convergence of the thread
    joined = " ".join(c.get("text", "") for c in structured).lower()
    handoff_m = _HANDOFF.search(joined)
    handoff_team = ""
    if handoff_m:
        handoff_team = (handoff_m.group("team1") or handoff_m.group("team2") or "").strip()
    # A genuine closure needs a prose disposition, NOT an experiment-matrix hit.
    closed = any(w in joined for w in ("no repro", "cannot reproduce", "closing as",
                                       "closed as", "rejected")) and bool(resolution)
    if handoff_m and root_cause:
        team = f" ({handoff_team})" if handoff_team else ""
        status_hint = f"root-caused; handed off for the fix{team} — ticket open"
    elif closed:
        status_hint = "closed / resolved (see disposition)"
    elif workaround and root_cause:
        status_hint = "root-caused; workaround validated; real fix in progress"
    elif root_cause:
        status_hint = "root cause identified (unverified/fix pending)"
    elif "promoted to" in joined or "in progress" in joined:
        status_hint = "under active debug"
    else:
        status_hint = "early investigation"

    return {
        "count": len(structured),
        "narrative": narrative,
        "root_cause": root_cause,
        "root_cause_author": rc_author,
        "root_cause_source": rc_source,
        "workaround": workaround,
        "workaround_author": wa_author,
        "resolution": resolution,
        "resolution_author": res_author,
        "handoff_team": handoff_team,
        "tried": tried[:10],
        "next_steps": next_steps[:6],
        "breadcrumbs": crumbs,
        "status_hint": status_hint,
    }
