#!/usr/bin/env python3
"""
MCHECK Error Decoder - Decode Intel platform configuration check (MCHECK) error codes.

MCHECK is Intel's boot-time platform configuration validator that runs as part of
microcode during BIOS initialization.  When a check fails, the error code is written
to MSR_TEE_ERR_CODE and printed to the BIOS serial log.

Error codes come from the dfx_mapping definition file.  The database is generated by
parse_dfx_mapping.py.

@copyright
INTEL CONFIDENTIAL
Copyright (C) 2026 Intel Corporation.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent / "shared"))
from decoder_utils import load_json_database


_DEFAULT_DB_PATH = Path(__file__).parent / 'mcheck_codes_database.json'


def _normalize_key(hex_code: str) -> str:
    """
    Normalize a hex code string to the lowercase key used in the database.

    Examples:
        '0x250E'   -> '0x250e'
        '0X250E'   -> '0x250e'
        '0x0250e'  -> '0x250e'
        '250e'     -> '0x250e'
    """
    raw = hex_code.strip()
    if raw.upper().startswith('0X'):
        raw = raw[2:]
    try:
        return hex(int(raw, 16))   # hex() returns lowercase '0x...'
    except ValueError:
        return '0x' + raw.lower()


class McheckDecoder:
    """Decoder for Intel MCHECK (platform configuration check) error codes."""

    def __init__(self, db_path=None):
        """
        Initialize the decoder.

        Args:
            db_path: Path to mcheck_codes_database.json.  Defaults to the bundled
                     database next to this script.
        """
        if db_path is None:
            db_path = _DEFAULT_DB_PATH
        self._db = load_json_database(str(db_path), default={})
        if self._db:
            print(
                f"✓ Loaded {len(self._db)} MCHECK error codes from database",
                file=sys.stderr
            )
        else:
            print(
                "⚠ MCHECK database not loaded — decode will return not-found for all codes",
                file=sys.stderr
            )

    def decode(self, hex_code: str) -> dict:
        """
        Decode a single MCHECK error code.

        Args:
            hex_code: Hex string such as '0x250e', '0X250E', '250e'.

        Returns:
            dict with keys:
                code            str   normalised hex code (e.g. '0x250e')
                name            str | None
                description     str | None
                dfx_group_name  str | None
                dfx_group_id    int | None
                dfx_bit_name    str | None
                dfx_bit_id      int | None
                found           bool
        """
        key = _normalize_key(hex_code)
        entry = self._db.get(key)

        if entry:
            return {
                'code': key,
                'name': entry.get('name'),
                'description': entry.get('description'),
                'dfx_group_name': entry.get('dfx_group_name'),
                'dfx_group_id': entry.get('dfx_group_id'),
                'dfx_bit_name': entry.get('dfx_bit_name'),
                'dfx_bit_id': entry.get('dfx_bit_id'),
                'found': True,
            }

        return {
            'code': key,
            'name': None,
            'description': None,
            'dfx_group_name': None,
            'dfx_group_id': None,
            'dfx_bit_name': None,
            'dfx_bit_id': None,
            'found': False,
        }

    def format_decode(self, hex_code: str) -> str:
        """
        Return a human-readable decode string for a single MCHECK error code.

        Args:
            hex_code: Hex string to decode.

        Returns:
            Markdown-formatted string.
        """
        result = self.decode(hex_code)
        lines = [f"### MCHECK Code Decode\n"]
        lines.append(f"\n**Code**: `{result['code']}`\n")

        if result['found']:
            if result['name']:
                lines.append(f"**Name**: {result['name']}\n")
            if result['description']:
                lines.append(f"**Description**: {result['description']}\n")
            if result['dfx_group_name']:
                lines.append(
                    f"**DFX Group**: {result['dfx_group_name']} ({result['dfx_group_id']})\n"
                )
            if result['dfx_bit_name']:
                lines.append(
                    f"**DFX Bit**: {result['dfx_bit_name']} ({result['dfx_bit_id']})\n"
                )
        else:
            lines.append("**Status**: Code not found in MCHECK database\n")

        return ''.join(lines)
